# --- SERVER PODE?AVANJA (HTTPS) ---
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bsep-backend

# --- BAZA PODATAKA (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/bsep_pki_db
spring.datasource.username=bsep_user
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
# Ovo automatski pravi tabele u bazi na osnovu tvojih Java klasa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- UPLOAD LIMITI (Za CSR fajlove kasnije) ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Swagger/OpenAPI konfiguracija
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.use-root-path=false
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.default-models-expand-depth=1
springdoc.swagger-ui.default-model-expand-depth=1
springdoc.swagger-ui.doc-expansion=list
server.servlet.context-path=/

# Email konfiguracija (Gmail - SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=onlybunsisa5@gmail.com
spring.mail.password=jvmeyqfudndkmgrt
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# Frontend URL za aktivacioni link 24h = 86400000ms aktivan
app.frontend.url=https://localhost:5173
app.activation.token.expiry=86400000 

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/sertifikat

# Generiši ga koristeći online generator za 32-byte (256-bit) Base64 ključ
aes.master.key=uN7vT6pS9zWvB4yA7fE2hJ1kM5nQ8rT4uW3xZ6aB9dC=

# Putanje za skladištenje fajlova -- Dje ovo tera ?
keystore.storage.path=./data/keystores
