# --- SERVER PODE?AVANJA (HTTPS) ---
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=123456
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=bsep-backend

# --- BAZA PODATAKA (PostgreSQL) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/bsep_pki_db
spring.datasource.username=bsep_user
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA / HIBERNATE ---
# Ovo automatski pravi tabele u bazi na osnovu tvojih Java klasa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# --- UPLOAD LIMITI (Za CSR fajlove kasnije) ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB